export const TOGGLE_ADD_FORM = 'TOGGLE_ADD_FORM'
export const TOGGLE_EDIT_FORM = 'TOGGLE_EDIT_FORM'
export const CLEAR_FORMS = 'CLEAR_FORMS'

export const HANDLE_TEXT_INPUT = 'HANDLE_TEXT_INPUT'
export const HANDLE_BOOL_CHANGE = 'HANDLE_BOOL_CHANGE'

export const VIEW_BUNNIES = 'VIEW_BUNNIES'
export const CHOOSE_BUNNY_TO_EDIT = 'CHOOSE_BUNNY_TO_EDIT'

export const TOGGLE_SHOW_ALERT = 'TOGGLE_SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const LOGIN_ADMIN = 'LOGIN_ADMIN'
export const LOGOUT_ADMIN = 'LOGOUT_ADMIN'

export const VIEW_APPLICATIONS = 'VIEW_APPLICATIONS'